version: "3"

services:
  api:
    build: .
    container_name: corona_api
    links:
      - redis:redis
    ports:
      - "8000:80"
    volumes:
      - ./app:/app

  redis:
    restart: always
    image: redis:latest

    volumes:
      - redisdata:/data

volumes:
  redisdata:
